[phases.setup]
nixPkgs = ['nodejs_18', 'npm']

[phases.install]
cmds = [
  'npm ci --prefix frontend',
  'npm ci --prefix backend'
]

[phases.build]
cmds = [
  'npm run build --prefix frontend'
]

[start]
cmd = 'cd backend && npm start'

[variables]
NODE_ENV = 'production'