[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
NODE_ENV = "production"
API_PREFIX = "/api/v1"
JWT_EXPIRES_IN = "12h"
JWT_REFRESH_EXPIRES_IN = "7d"
CORS_ORIGIN = "*"
RATE_LIMIT_WINDOW_MS = "900000"
RATE_LIMIT_MAX = "100"
MAX_FILE_SIZE = "5242880"
UPLOAD_DIR = "uploads"
LOG_LEVEL = "info"